// 'use servesr';

import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Login from '../components/Login'
import { getSession } from "next-auth/react"
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';

import { getDocs, collection, query, orderBy } from 'firebase/firestore';
import { db } from '../firebase'

const inter = Inter({ subsets: ['latin'] })

export default function Home({sessionExists, posts}) {
  if (!sessionExists) {return <Login />}
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Havir Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/* Header */}
      <Header />


      <main className='flex'>
        <Sidebar />
        <Feed posts={posts} />
        <Widgets />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  
  try {
    const session = await getSession(context);

    const posts =  await getDocs(query(collection(db, 'posts'), orderBy('timestamp', 'asc')))

    const mappedPosts = posts.docs.map((doc) =>  { return {
      id: doc.id,
      ...doc.data(),
      timestamp: null
      
    }})

    if (session) {
      return {
        props: {
          session,
          sessionExists: true,
          posts: mappedPosts
        }
      }
    }
    
  } catch (err) {
    console.log(err)
  }
    return {
      props: {
      }
    }
  
}