'use server';

import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Login from '../components/Login'
import { getSession } from "next-auth/react"
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  console.log(props)
  if (!props.sessionExists) {return <Login />}
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Habibibook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/* Header */}
      <Header />


      <main className='flex'>
        <Sidebar />
        <Feed />
        {/* Widgets */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  
  try {
    const session = await getSession(context);
    // console.log('TUTAJ', session)
    if (session) {
      return {
        props: {
          session,
          sessionExists: true
        }
      }
    }
    
  } catch (err) {
    console.log(err)
  }
    return {
      props: {
      }
    }
  
}